Feature/table employees
cv-gen-team/cv-gen-fe-2 pull request #41
Opened 2022-09-14 16:31 UTC by syantovich

2022-09-15 11:43 UTC, tatsmaki requested changes

2022-09-15 11:43 UTC, tatsmaki commented on src/components/pages/Employees/components/TablePaginationsActions/TablePaginationsActions.tsx
> +export const TablePaginationActions = (props: TablePaginationActionsProps) => {
зачем по итогу пагинация?

2022-09-15 11:43 UTC, tatsmaki commented on src/components/pages/Employees/components/Table/Table.tsx
> +                key={index}
без index как ключа, замени на что-нибудь

2022-09-15 11:43 UTC, tatsmaki commented on src/components/pages/Employees/Employees.tsx
> +  console.log(data, loading);
eslint no-console rule?

2022-09-15 11:43 UTC, tatsmaki commented on src/components/pages/Employees/Employees.tsx
> +                    last_name: e.profile.last_name,
зачем этот бесполезный маппинг?

2022-09-15 11:43 UTC, tatsmaki commented on src/components/pages/Employees/Employees.tsx
> +                    last_name: e.profile.last_name,
бесполезный потому что ничего не переименовывает
и даже если надо переименовать это делается на уровне запроса/сервиса/контейнера данных (не в компоненте который непосредственно отображает верстку)

2022-09-15 11:43 UTC, tatsmaki commented on src/components/pages/Employees/components/Table/Table.tsx
> +export const TableEmployees = ({ columns, textAlign = 'left', rows }: TableEmployeeTypeProps) => {
export default memo(TableEmployees)

2022-09-15 11:43 UTC, tatsmaki commented on src/components/pages/Employees/components/Table/Table.tsx
> +              {columns.map(({ field }, index) => (
а если в данных лишние поля или поля которые надо отобразить не просто текстом?

2022-09-15 11:43 UTC, tatsmaki commented on src/components/templates/router/router.tsx
> +                <PageWithNavbar>
гуд, потом можно будет все страницы с Navbar обернуть в общий роут по аналогии с AuthTabs

2022-09-16 13:03 UTC, tatsmaki requested changes

2022-09-16 13:03 UTC, tatsmaki commented on src/components/pages/Employees/components/Table/Table.tsx
> +const TableEmployees = ({ TableHeader, TableBody, TableFooter }: TableProps) => {
TableEmployees? то есть это не универсальная таблица?

2022-09-16 13:03 UTC, tatsmaki commented on src/components/pages/Employees/components/Table/Table.tsx
> +          <TableBody key={'body'} props={{}} type={'body'} />
items.map(() => \<TableRow  \/>)

2022-09-16 13:03 UTC, tatsmaki commented on src/hooks/useGetEmployees/useGetEmployees.ts
> +  useEffect(() => {
убрать эффект

2022-09-16 13:03 UTC, tatsmaki commented on src/components/pages/Employees/components/EmployeeBodyTable/EmployeeBodyTable.tsx
> +export const EmployeeBodyTable: FC<JSX.Element> = () => {
убрать этот компонент, заменить на EmployeeTableRow

2022-09-17 13:15 UTC, tatsmaki requested changes

2022-09-17 13:15 UTC, tatsmaki commented on src/components/pages/Employees/components/EmployeeHeaderTable/EmployeeHeaderTable.tsx
> +            onClick={() => {
а зачем инлайн функцию везде дублируешь? в общий хэндлер вынеси

2022-09-17 13:15 UTC, tatsmaki commented on src/components/pages/Employees/components/Table/Table.tsx
> +  const { data } = useGetEmployees();
все еще не универсальная таблица, почему запрос делается в ней?

2022-09-17 13:15 UTC, tatsmaki commented on src/components/pages/Employees/components/Table/Table.tsx
> +                  for (const value of Object.values(user)) {
добавь к таблице проп searchFields: string[]
желательно с использованием keyof IUser
и ищи только по ключам в этом массиве
для юзеров это ['first_name', 'last_name'] или ['full_name']

2022-09-17 13:15 UTC, tatsmaki commented on src/components/pages/Employees/components/Table/Table.tsx
> +          {TableHeader && <TableHeader />}
аналогично с searchFields, sortFields: string[]

2022-09-17 13:15 UTC, tatsmaki commented on src/components/pages/Employees/components/EmployeeBodyTable/EmployeeBodyTable.tsx
> +      <TableCell sx={{ ...columnsSetting[TableEmployeeEnum.firstName].sx, ...TableRowsSX }}>{firstName}</TableCell>
честно говоря стили выглядят страшно и я не понимаю почему это нельзя было сделать в EmployeeRowTable.styles.ts

2022-09-17 13:15 UTC, tatsmaki commented on src/components/pages/Employees/components/EmployeeBodyTable/EmployeeBodyTable.tsx
> +      <TableCell sx={{ ...columnsSetting[TableEmployeeEnum.firstName].sx, ...TableRowsSX }}>{firstName}</TableCell>
имя компонента не совпадает с именем папки

2022-09-17 13:15 UTC, tatsmaki commented on src/components/pages/Employees/components/EmployeeHeaderTable/EmployeeHeaderTable.tsx
> +            onClick={() => {
в общий хэндлер

2022-09-17 13:15 UTC, tatsmaki commented on src/components/pages/Employees/components/EmployeeHeaderTable/EmployeeHeaderTable.tsx
> +            onClick={() => {
в общий хэндлер

2022-09-17 13:15 UTC, tatsmaki commented on src/components/pages/Employees/components/EmployeeHeaderTable/EmployeeHeaderTable.tsx
> +            onClick={() => {
в общий хэндлер

2022-09-17 13:15 UTC, tatsmaki commented on src/components/pages/Employees/components/EmployeeHeaderTable/EmployeeHeaderTable.tsx
> +            onClick={() => {
в общий хэндлер

2022-09-17 13:15 UTC, tatsmaki commented on src/hooks/useGetEmployees/useGetEmployees.ts
> +      last_name: e.profile.last_name || '',
избавься от этого маппинга, пожалуйста, прокидывай в таблицу все данные как есть и отображай что нужно в EmployeeTableRow

2022-09-19 17:10 UTC, syantovich commented on src/components/pages/Employees/Employees.tsx
> +          TableRow={EmployeeRowTable}
тут ошибка
![image](https://user-images.githubusercontent.com/72738946/191074242-b7edd44c-9497-4b9a-bbdf-bc33c4b26b89.png)

2022-09-26 12:58 UTC, merged